//
//  HomePresenter.swift
//  ququququ
//
//  Created by Buratsakorn Petchdee on 21/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol HomePresentationLogic {
    func presentResponse(viewModel: HomeModel.Response)
    func listResponse(viewModel: [HomeModel.List])
}

final class HomePresenter {
  private weak var viewController: HomeDisplayLogic?
  
  init(viewController: HomeDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - HomePresentationLogic
extension HomePresenter: HomePresentationLogic {
    func presentResponse(viewModel: HomeModel.Response) {
        viewController?.displayViewModel(viewModel)

    }
    func listResponse(viewModel : [HomeModel.List]){
        viewController?.displayListModel(viewModel)
    }
    
}
