//
//  HomeViewController.swift
//  ququququ
//
//  Created by Buratsakorn Petchdee on 21/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic where Self: UIViewController {
    
    func displayViewModel(_ viewModel: HomeModel.Response)
    func displayListModel(_ viewModel: [HomeModel.List])
    
}

class HomeViewController: UIViewController {
    private var interactor: HomeInteractable!
    private var router: HomeRouting!
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var subLabel: UILabel!
    
    @IBOutlet weak var branchBtn: UIButton!
    @IBOutlet weak var bookBtn: UIButton!
    
    var list = [HomeModel.List]()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor = HomeInteractor(viewController: self)
        router = HomeRouter(viewController: self)
        tableView.delegate = self
        tableView.dataSource = self
        tableView.register(UINib(nibName: "HomeViewCell", bundle: nil), forCellReuseIdentifier: "HomeViewCell")
        registerTableView()
        self.tableView.reloadData()
        interactor.doTitleRequest()
        interactor.doQueueList()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
    }
    
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
    }
    
    @IBAction func onQueueTap() {
        guard let queue = storyboard?.instantiateViewController(withIdentifier: "BookingViewController")as? BookingViewController else {
            return
            
        }
        present(queue, animated: true)
              self.navigationController?.pushViewController(queue, animated: true)
    }
    
    
    @IBAction func onBranchTap() {
        let queueStoryboard = UIStoryboard(name: "QueueStoryboard", bundle: nil)
        guard let branch = queueStoryboard.instantiateViewController(withIdentifier: "QueueViewController")as? QueueViewController else{
            
            return
        }
        self.navigationController!.pushViewController(branch, animated: true)
        //present(branch, animated: true)
        
    }
    private func registerTableView() {
        let cellNib = UINib(nibName: "HomeViewCell", bundle: nil)
        tableView.register(cellNib, forCellReuseIdentifier: "HomeViewCell")
    }
}





extension HomeViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return list.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "HomeViewCell", for: indexPath) as? HomeViewCell else {
            return UITableViewCell()
        }
        // cell.branchdes.text = HomeModel[indexPath.row].account
        cell.branchdes.text = list[indexPath.row].branch
        cell.accountdesc.text = list[indexPath.row].account
        cell.processdesc.text = list[indexPath.row].process
        cell.datedesc.text = list[indexPath.row].date
        cell.setupProcessStatus(status: list[indexPath.row].process ?? "")
        return cell
    }
}



// MARK: - HomeDisplayLogic
extension HomeViewController: HomeDisplayLogic {
    
    func displayViewModel(_ viewModel: HomeModel.Response) {
        DispatchQueue.main.async {
            self.nameLabel.text = viewModel.name
            self.subLabel.text =    viewModel.sub
        }
    }
    func displayListModel(_ viewModel: [HomeModel.List]){
        DispatchQueue.main.async {
            self.list = viewModel
            self.tableView.reloadData()
        }
    }
    
}


// MARK: - HomeViewDelegate
extension HomeViewController: HomeViewDelegate {
    
    func sendDataBackToParent(_ data: Data) {
        //usually this delegate takes care of users actions and requests through UI
        
        //do something with the data or message send back from mainView
    }
}


// MARK: - Private Zone
private extension HomeViewController {
    
    func displayDoSomething(_ viewModel: HomeModel.Response) {
    }
}
