//
//  HomeViewController.swift
//  ququququ
//
//  Created by Buratsakorn Petchdee on 21/2/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic where Self: UIViewController {
    
    func displayViewModel(_ viewModel: HomeModel.Response)
}

class HomeViewController: UIViewController {
    private var interactor: HomeInteractable!
    private var router: HomeRouting!
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var nameLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor = HomeInteractor(viewController: self)
        router = HomeRouter(viewController: self)
        tableView.delegate = self
        tableView.dataSource = self
        registerTableView()
        
        interactor.doRequest()
    }
    
    private func registerTableView() {
        let cellNib = UINib(nibName: "HomeViewCell", bundle: nil)
        tableView.register(cellNib, forCellReuseIdentifier: "HomeViewCell")
    }
}

extension HomeViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 6
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "HomeViewCell", for: indexPath) as? HomeViewCell else {
            return UITableViewCell()
        }
        return cell
    }
}

// MARK: - HomeDisplayLogic
extension HomeViewController: HomeDisplayLogic {
    
    func displayViewModel(_ viewModel: HomeModel.Response) {
        DispatchQueue.main.async {
            self.nameLabel.text = viewModel.name
        }
    }
}


// MARK: - HomeViewDelegate
extension HomeViewController: HomeViewDelegate {
    
    func sendDataBackToParent(_ data: Data) {
        //usually this delegate takes care of users actions and requests through UI
        
        //do something with the data or message send back from mainView
    }
}


// MARK: - Private Zone
private extension HomeViewController {
    
    func displayDoSomething(_ viewModel: HomeModel.Response) {
    }
}
