//
//  MapInteractor.swift
//  ququququ
//
//  Created by Buratsakorn Petchdee on 17/3/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation


protocol MapBusinessLogic {
    func fetchLocations()
}

class MapInteractor {
    
    
    private var presenter: MapPresentationLogic
    
    init(viewController: MapDisplayLogic?) {
        self.presenter = MapPresenter(viewController: viewController)
    }
    
    func fetchLocations() {
        let url = URL(string: "http://localhost:8882/locations")!

        let task = URLSession.shared.dataTask(with: url, completionHandler: { (data, response, error) in
            let jsonDecoder = JSONDecoder()
            let model = try! jsonDecoder.decode([MapModel.Location].self, from: data!)
            self.presenter.displayLocations(locations: model)
        })

        task.resume()
    }
      
}


// MARK: - MapBusinessLogic
extension MapInteractor: MapBusinessLogic {
    
}







