//
//  MapModel.swift
//  ququququ
//
//  Created by Buratsakorn Petchdee on 17/3/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum MapModel {
  
    struct Location: Codable {
      var latitude: String
      var longitude: String
      var location: String
  }
}
