//
//  MapPresenter.swift
//  ququququ
//
//  Created by Buratsakorn Petchdee on 17/3/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol MapPresentationLogic {
    func displayLocations(locations: [MapModel.Location])
}

final class MapPresenter {
  private weak var viewController: MapDisplayLogic?
  
  init(viewController: MapDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - MapPresentationLogic
extension MapPresenter: MapPresentationLogic {
    func displayLocations(locations: [MapModel.Location]) {
        viewController?.displayLocations(locations: locations)
    }
}

